gr_1_projekt/gr_1_projekt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wypozyczalnia_filmow/', include('wypozyczalnia_filmow.urls')),
]

gr_1_projekt/wypozyczalnia_filmow/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    
    path('filmy/', views.FilmList.as_view(), name='film-list'),
    path('filmy/<int:pk>/', views.FilmDetail.as_view(), name='film-detail'),
    path('rezyserzy/', views.RezyserList.as_view(), name='rezyser-list'),
    path('osoby/', views.OsobaList.as_view(), name='osoba-list'),
    path('stanowiska/', views.StanowiskoList.as_view(), name='stanowisko-list'),
    path('welcome/', views.welcome, name='welcome'),

    
    path('html/osoby/', views.osoba_list_html, name='osoba-list-html'),
    path('html/osoby/<int:id>/', views.osoba_detail_html, name='osoba-detail-html'),
    path('html/osoby/dodaj/', views.osoba_create_html, name='osoba-create'),
    path('html/osoby/edytuj/<int:id>/', views.osoba_edit_html, name='osoba-edit-html'),

  
    path('html/filmy/', views.film_list_html, name='film-list-html'),
    path('html/filmy/<int:id>/', views.film_detail_html, name='film-detail-html'),
    path('html/filmy/dodaj/', views.film_create_html, name='film-create-html'),
    path('html/filmy/edytuj/<int:id>/', views.film_edit, name='film-edit-html'),
    path('html/filmy/szukaj/', views.film_search, name='film-search-html'),
    path('html/filmy/losuj/', views.random_movie_page, name='film-random-page'),

    path('html/gatunki/', views.gatunek_list_html, name='gatunek-list-html'),
    path('html/gatunki/dodaj/', views.gatunek_create_html, name='gatunek-create-html'),
    path('html/gatunki/<int:id>/', views.gatunek_detail_html, name='gatunek-detail-html'),
    path('html/gatunki/edytuj/<int:id>/', views.gatunek_edit_html, name='gatunek-edit-html'),
    

    path('html/rezyserzy/', views.rezyser_list_html, name='rezyser-list-html'), 
    path('html/rezyserzy/<int:id>/', views.rezyser_detail_html, name='rezyser-detail-html'), 
    path('html/rezyserzy/nowy/', views.rezyser_create_html, name='rezyser-create-html'),
    path('html/rezyserzy/edytuj/<int:id>/', views.rezyser_edit_html, name='rezyser-edit-html'),

    path('html/stanowiska/', views.stanowisko_list_html, name='stanowisko-list-html'),
    path('html/stanowiska/nowe/', views.stanowisko_create_html, name='stanowisko-create-html'),
    path('html/stanowiska/<int:id>/', views.stanowisko_detail_html, name='stanowisko-detail-html'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('html/stanowiska/usun/<int:id>/', views.stanowisko_delete_html, name='stanowisko-delete-html'),
    path('html/stanowiska/edytuj/<int:id>/', views.stanowisko_edit_html, name='stanowisko-edit-html'),


    path('accounts/', include('django.contrib.auth.urls')),
    path('rejestracja/', views.rejestracja, name='register'),

]

gr_1_projekt/wypozyczalnia_filmow/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import UniqueConstraint
from django.core.validators import MaxValueValidator, MinValueValidator

MIESIACE = models.IntegerChoices(
    'Miesiace',
    'Styczeń Luty Marzec Kwiecień Maj Czerwiec Lipiec Sierpień Wrzesień Październik Listopad Grudzień'
)

FORMAT_FILMU = (
    ('D', 'DVD'),
    ('B', 'Blu-ray'),
    ('V', 'VOD'),
)

class Gatunek(models.Model):
    nazwa = models.CharField(max_length=50)
    opis = models.TextField(blank=True)
    typowe_motywy = models.CharField(max_length=200, blank=True)
    czy_fabularny = models.BooleanField(default=True)
    

    def __str__(self):
        return self.nazwa    
        
    class Meta:
        ordering = ['nazwa']
        verbose_name = "Gatunek"
        verbose_name_plural = "Gatunki"
        

class Rezyser(models.Model):
    imie = models.CharField(max_length=50)
    nazwisko = models.CharField(max_length=50)
    kraj = models.CharField(max_length=2, help_text="Kod kraju, np. PL, US, GB")

    def __str__(self):
        return f"{self.imie} {self.nazwisko}"

    class Meta:
        ordering = ['nazwisko', 'imie']
        verbose_name = "Reżyser"
        verbose_name_plural = "Reżyserzy"
        constraints = [
            UniqueConstraint(fields=['imie', 'nazwisko'], name='unique_rezyser_name')
        ]
           


class Film(models.Model):
    tytul = models.CharField(max_length=168)
    miesiac_premiery = models.IntegerField(choices=MIESIACE.choices, default=MIESIACE.Styczeń)
    format_filmu = models.CharField(max_length=1, choices=FORMAT_FILMU, default='D')
    rezyser = models.ForeignKey(Rezyser, null=True, blank=True, on_delete=models.SET_NULL)
    gatunek = models.ForeignKey(Gatunek, null=True, blank=True, on_delete=models.SET_NULL)
    dostepne_kopie = models.PositiveIntegerField(default=1)

   
    
    def __str__(self):
        return self.tytul    
    
    
    class Meta:
        ordering = ['tytul']
        verbose_name = "Film"
        verbose_name_plural = "Filmy"
        constraints = [
            models.CheckConstraint(condition=models.Q(dostepne_kopie__gte=0), name='kopie_nieujemne'),
        ]
        



PLCIE = models.IntegerChoices(
    'Plcie',
    'Kobieta Mezczyzna Inna'
)
   
class Osoba(models.Model):
    PLEC_WYBOR = (
        ("K", "kobieta"),
        ("M", "mezczyzna"),
        ("I", "inna")
    )
    imie = models.CharField(max_length=50, blank = False, null = False)
    nazwisko = models.CharField(max_length=100, blank = False, null = False)
    plec = models.IntegerField(choices=PLCIE.choices, default=PLCIE.Inna)
    stanowisko = models.ForeignKey('Stanowisko', on_delete=models.CASCADE)
    data_dodania = models.DateField(auto_now_add=True, editable= False)
    wlasciciel = models.ForeignKey(User, on_delete = models.SET_NULL, null = True, default = 1) 
    
    def __str__(self):
        return f"Osoba: {self.imie} {self.nazwisko}"
   
    class Meta:
        ordering = ['nazwisko']
        verbose_name = "Osoba"
        verbose_name_plural = "Osoby"
        permissions = [
            ("can_view_other_persons", "Może przeglądać inne osoby"),
            ("change_osoba_owner", "Może zmienić właściciela rekordu"),
        ]
        

    
class Stanowisko(models.Model):
    nazwa = models.CharField(max_length=50, blank = False, null = False)
    opis = models.TextField(blank = True, null = True) 
    
    def __str__(self):
        return self.nazwa

    class Meta:
        ordering = ['nazwa']
        verbose_name = "Stanowisko"
        verbose_name_plural = "Stanowiska"
        

gr_1_projekt/wypozyczalnia_filmow/forms.py
from django import forms
from .models import Gatunek, Rezyser, Film, Osoba, Stanowisko 

class OsobaForm(forms.ModelForm):
    class Meta:
        model = Osoba
        fields = ['imie', 'nazwisko', 'plec', 'stanowisko']



class FilmForm(forms.ModelForm):
    class Meta:
        model = Film
        fields = ['tytul', 'miesiac_premiery','format_filmu','rezyser','gatunek', 'dostepne_kopie' ]
            
           


class StanowiskoForm(forms.ModelForm):
    class Meta:
        model = Stanowisko
        fields = ['nazwa', 'opis']
            

       

gr_1_projekt/wypozyczalnia_filmow/views.py
from rest_framework import generics
from .models import Film, Rezyser, Gatunek, Osoba, Stanowisko
from .serializers import (
    FilmSerializer, RezyserSerializer, GatunekSerializer, 
    OsobaSerializer, StanowiskoSerializer
)
import datetime
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404, HttpResponse
from django.contrib.auth.decorators import login_required
from rest_framework import generics, status
from rest_framework.response import Response
from .forms import OsobaForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
import random
from .forms import FilmForm
from django.contrib.auth.decorators import user_passes_test
from .forms import StanowiskoForm





class FilmList(generics.ListCreateAPIView):
    queryset = Film.objects.all()
    serializer_class = FilmSerializer

class FilmDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Film.objects.all()
    serializer_class = FilmSerializer



class RezyserList(generics.ListCreateAPIView):
    queryset = Rezyser.objects.all()
    serializer_class = RezyserSerializer

class RezyserDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Rezyser.objects.all()
    serializer_class = RezyserSerializer



class GatunekList(generics.ListCreateAPIView):
    queryset = Gatunek.objects.all()
    serializer_class = GatunekSerializer

class GatunekDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Gatunek.objects.all()
    serializer_class = GatunekSerializer



class OsobaList(generics.ListCreateAPIView):
    queryset = Osoba.objects.all()
    serializer_class = OsobaSerializer

class OsobaDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Osoba.objects.all()
    serializer_class = OsobaSerializer



class StanowiskoList(generics.ListCreateAPIView):
    queryset = Stanowisko.objects.all()
    serializer_class = StanowiskoSerializer

class StanowiskoDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Stanowisko.objects.all()
    serializer_class = StanowiskoSerializer

def welcome(request):
    now = datetime.datetime.now()
    return render(request, 'welcome.html', {'current_time': now})


def film_list_html(request):
    if request.method == "POST":
        form = FilmForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('film-list-html')
    else:
        form = FilmForm()

    filmy = Film.objects.all()
    
    return render(request, "wypozyczalnia_filmow/film/list.html", {
        'filmy': filmy, 
        'form': form
    })

def film_detail_html(request, id):
    film = get_object_or_404(Film, id=id)
    if request.method == "POST":
        film.delete()
        return redirect('film-list-html')
    return render(request, "wypozyczalnia_filmow/film/detail.html", {'film': film})


def film_create_html(request):
    if request.method == "POST":
        serializer = FilmSerializer(data=request.POST)
        form = FilmForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('film-list-html')
    else:
        form = FilmForm()
    
    return render(request, "wypozyczalnia_filmow/film/create.html", {'form': form})

def film_edit(request, id):
    film = get_object_or_404(Film, id=id)
    if request.method == "POST":
        form = FilmForm(request.POST, instance=film)
        if form.is_valid():
            form.save()
            return redirect('film-list-html')
    else:
        form = FilmForm(instance=film)
    return render(request, 'wypozyczalnia_filmow/film/form.html', {'form': form, 'title': 'Edytuj film'})


def film_search(request):
    query = request.GET.get('q') 
    if query:
        filmy = Film.objects.filter(tytul__icontains=query)
    else:
        filmy = Film.objects.all()
    

    return render(request, 'wypozyczalnia_filmow/film/search.html', {'filmy': filmy, 'query': query})


def random_movie_page(request):
    wszystkie_filmy = Film.objects.all()
    
    losowy_film = None
    if wszystkie_filmy.exists():
        losowy_film = random.choice(wszystkie_filmy)
    

    return render(request, 'wypozyczalnia_filmow/film/random_result.html', {
        'film': losowy_film
    })



def osoba_list_html(request):
    osoby = Osoba.objects.all()
    return render(request, "wypozyczalnia_filmow/osoba/list.html", {'osoby': osoby})    



def osoba_detail_html(request, id):
    osoba = get_object_or_404(Osoba, id=id)
    if request.method == "POST":
        osoba.delete()
        return redirect('osoba-list-html')
    return render(request, "wypozyczalnia_filmow/osoba/detail.html", {'osoba': osoba})


@user_passes_test(lambda u: u.is_superuser)
def osoba_create_html(request):
    stanowiska = Stanowisko.objects.all()
    if request.method == "POST":
        imie = request.POST.get('imie')
        nazwisko = request.POST.get('nazwisko')
        
        
        plec_raw = request.POST.get('plec')

        plec = 2 if plec_raw in ['K', '2'] else 1 
        
        stanowisko_id = request.POST.get('stanowisko')

        serializer = OsobaSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return redirect('osoba-list-html')
        errors = serializer.errors

        if imie and nazwisko and stanowisko_id:
            stanowisko_obj = get_object_or_404(Stanowisko, id=stanowisko_id)
            Osoba.objects.create(
                imie=imie, 
                nazwisko=nazwisko, 
                plec=plec, 
                stanowisko=stanowisko_obj
            )
            return redirect('osoba-list-html')
            
    return render(request, "wypozyczalnia_filmow/osoba/create.html", {'stanowiska': stanowiska})

@user_passes_test(lambda u: u.is_superuser)
def osoba_edit_html(request, id):
    osoba = get_object_or_404(Osoba, id=id)
    errors = None
    if request.method == "POST":
        data = request.POST.copy()
        data['plec'] = 2 if data.get('plec') in ['K', '2', 'Kobieta'] else 1
        serializer = OsobaSerializer(instance=osoba, data=data)
        if serializer.is_valid():
            serializer.save()
            return redirect('osoba-list-html')
        errors = serializer.errors
    return render(request, "wypozyczalnia_filmow/osoba/create.html", {
        'osoba': osoba, 
        'errors': errors, 
        'stanowiska': Stanowisko.objects.all()
    })

@user_passes_test(lambda u: u.is_superuser)
def osoba_list_html(request):
    osoby = Osoba.objects.all()
    return render(request, 'wypozyczalnia_filmow/osoba/list.html', {'osoby': osoby})


def gatunek_list_html(request):
    gatunki = Gatunek.objects.all()
    return render(request, "wypozyczalnia_filmow/gatunek/list.html", {'gatunki': gatunki})

def gatunek_create_html(request):
    if request.method == "POST":
        serializer = GatunekSerializer(data=request.POST)
        nazwa = request.POST.get('nazwa')
        opis = request.POST.get('opis')
        typowe_motywy = request.POST.get('typowe_motywy')
        czy_fabularny = request.POST.get('czy_fabularny') == 'on'

        if nazwa:
            Gatunek.objects.create(
                nazwa=nazwa, opis=opis, 
                typowe_motywy=typowe_motywy, czy_fabularny=czy_fabularny
            )
            return redirect('gatunek-list-html')
    return render(request, "wypozyczalnia_filmow/gatunek/create.html")

def gatunek_detail_html(request, id):
    gatunek = get_object_or_404(Gatunek, id=id)
    
    if request.method == "POST":
        gatunek.delete()
        return redirect('gatunek-list-html')
        
    return render(request, "wypozyczalnia_filmow/gatunek/detail.html", {'gatunek': gatunek})

def gatunek_edit_html(request, id):
    gatunek = get_object_or_404(Gatunek, id=id)
    errors = None
    if request.method == "POST":
        serializer = GatunekSerializer(instance=gatunek, data=request.POST)
        if serializer.is_valid():
            serializer.save()
            return redirect('gatunek-list-html')
        errors = serializer.errors
    return render(request, "wypozyczalnia_filmow/gatunek/create.html", {
        'gatunek': gatunek, 
        'errors': errors
    })


def rezyser_list_html(request):
    rezyserzy = Rezyser.objects.all()
    return render(request, "wypozyczalnia_filmow/rezyser/list.html", {'rezyserzy': rezyserzy})

def rezyser_create_html(request):
    if request.method == "POST":
        serializer = RezyserSerializer(data=request.POST)
        imie = request.POST.get('imie')
        nazwisko = request.POST.get('nazwisko')
        kraj = request.POST.get('kraj')
        if imie and nazwisko:
            Rezyser.objects.create(imie=imie, nazwisko=nazwisko, kraj=kraj)
            return redirect('rezyser-list-html')
    return render(request, "wypozyczalnia_filmow/rezyser/create.html")

def rezyser_detail_html(request, id):
    rezyser = get_object_or_404(Rezyser, id=id)
    if request.method == "POST":
        rezyser.delete()
        return redirect('rezyser-list-html')
    return render(request, "wypozyczalnia_filmow/rezyser/detail.html", {'rezyser': rezyser})


def rezyser_edit_html(request, id):
    rezyser = get_object_or_404(Rezyser, id=id)
    errors = None
    if request.method == "POST":
        serializer = RezyserSerializer(instance=rezyser, data=request.POST)
        if serializer.is_valid():
            serializer.save()
            return redirect('rezyser-list-html')
        errors = serializer.errors
    return render(request, "wypozyczalnia_filmow/rezyser/create.html", {
        'rezyser': rezyser, 
        'errors': errors
    })




def film_detail_html(request, id):
    film = get_object_or_404(Film, id=id)
    if request.method == "POST":
        film.delete()
        return redirect('film-list-html')
    return render(request, "wypozyczalnia_filmow/film/detail.html", {'film': film})

gr_1_projekt/wypozyczalnia_filmow/templates/wypozyczalnia_filmow/film/create.html
<!DOCTYPE html>
<html>
<head>
    <title>Dodaj nowy film</title>
</head>
<body>
    <h2>Dodaj nowy film</h2>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Zapisz film</button>
    </form>

    <br>
    <a href="{% url 'film-list-html' %}">Powrót do listy filmów</a>
</body>
</html>

gr_1_projekt/wypozyczalnia_filmow/templates/wypozyczalnia_filmow/film/detail.html
<h2>Szczegóły filmu: {{ film.tytul }}</h2>
<p><strong>Miesiąc premiery:</strong> {{ film.get_miesiac_premiery_display }}</p>
<p><strong>Gatunek:</strong> {{ film.gatunek.nazwa }}</p>
<p><strong>Reżyser:</strong> {{ film.rezyser.imie }} {{ film.rezyser.nazwisko }}</p>
<p><strong>Dostępne kopie:</strong> {{ film.dostepne_kopie }}</p>

<form method="POST">
    {% csrf_token %}
    <button type="submit">Usuń film</button>
</form>

<hr>
<a href="{% url 'film-list-html' %}">Wróć do listy filmów</a>

gr_1_projekt/wypozyczalnia_filmow/templates/wypozyczalnia_filmow/film/form.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
    <style>
        body { font-family: sans-serif; padding: 30px; }
        .container { max-width: 500px; margin: auto; border: 1px solid #ccc; padding: 20px; border-radius: 10px; }
        form p { margin-bottom: 15px; }
        input, select { width: 100%; padding: 8px; }
        button { background: #007bff; color: white; border: none; padding: 10px 20px; cursor: pointer; }
    </style>
</head>
<body>
    <div class="container">
        <h2>{{ title }}</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Zapisz</button>
        </form>
        <br>
        <a href="{% url 'film-list-html' %}">Anuluj</a>
    </div>
</body>
</html>

gr_1_projekt/wypozyczalnia_filmow/templates/wypozyczalnia_filmow/film/list.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>Lista Filmów</title>
</head>
<body>
    <p>Zalogowany jako: <strong>{{ user.username }}</strong> | 
       <a href="{% url 'film-list-html' %}">Filmy</a> | 
       <a href="{% url 'rezyser-list-html' %}">Reżyserzy</a> | 
       <a href="{% url 'gatunek-list-html' %}">Gatunki</a> 
       {% if user.is_superuser %}
            | <a href="{% url 'osoba-list-html' %}" style="color: red;">Osoby (Admin)</a> | 
            <a href="{% url 'stanowisko-list-html' %}" style="color: red;">Stanowiska (Admin)</a>
       {% endif %}
       | <a href="{% url 'logout' %}" style="color: red; margin-left: 10px;">Wyloguj się</a>
    </p>

    <h2>Lista Filmów</h2>
    
    <nav>
        <a href="{% url 'film-create-html' %}">+ Dodaj nowy film</a> | 
        <a href="{% url 'film-search-html' %}">Szukaj filmu</a> | 
        <a href="{% url 'film-random-page' %}">Losuj film</a>
    </nav>

    <hr>

    <table border="1" style="width: 100%; border-collapse: collapse; margin-top: 10px;">
        <thead>
            <tr style="background-color: #f2f2f2;">
                <th style="padding: 8px;">Tytuł</th>
                <th style="padding: 8px;">Reżyser</th>
                <th style="padding: 8px;">Akcje</th>
            </tr>
        </thead>
        <tbody>
            {% for f in filmy %}
            <tr>
                <td style="padding: 8px;">{{ f.tytul }}</td>
                <td style="padding: 8px;">{{ f.rezyser.imie }} {{ f.rezyser.nazwisko }}</td>
                <td style="padding: 8px; text-align: center;">
                    <a href="{% url 'film-detail-html' f.id %}">Szczegóły</a>
                    {% if user.is_superuser %}
                        | <a href="{% url 'film-edit-html' f.id %}" style="color: orange;">Edytuj</a>
                    {% endif %}
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3" style="padding: 8px; text-align: center;">Brak filmów w bazie danych.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <hr>
    <a href="{% url 'welcome' %}">« Powrót do menu głównego</a>
</body>
</html>

gr_1_projekt/wypozyczalnia_filmow/templates/wypozyczalnia_filmow/film/random_result.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>Losowanie Filmu</title>
    <style>
        body { font-family: sans-serif; background: #1a1a1a; color: #eee; text-align: center; padding: 50px; }
        .card { background: #2d2d2d; border: 3px solid #f39c12; border-radius: 15px; padding: 40px; display: inline-block; min-width: 300px; }
        .btn-again { background: #f39c12; color: white; padding: 12px 24px; text-decoration: none; border-radius: 5px; font-weight: bold; display: inline-block; margin-top: 20px; }
        .back-link { display: block; margin-top: 30px; color: #999; text-decoration: none; }
    </style>
</head>
<body>

    <h1>✨ Rekomendacja dla Ciebie ✨</h1>

    <div class="card">
        {% if film %}
            <h2 style="color: #f39c12;">{{ film.tytul }}</h2>
            <p>Gatunek: <b>{{ film.gatunek.nazwa }}</b></p>
            <p>Dostępne kopie: {{ film.dostepne_kopie }}</p>
            <br>
            <a href="{% url 'film-detail-html' film.id %}" style="color: #3498db;">➡ Szczegóły filmu</a>
        {% else %}
            <p>Brak filmów w bazie. Dodaj coś w panelu admina!</p>
        {% endif %}
    </div>

    <div>
        <a href="{% url 'film-random-page' %}" class="btn-again">WYLOSUJ INNY 🎲</a>
    </div>

    <a href="{% url 'welcome' %}" class="back-link">⬅ Wróć do strony głównej</a>

</body>
</html>

gr_1_projekt/wypozyczalnia_filmow/templates/wypozyczalnia_filmow/film/search.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>Wyszukiwarka Filmów</title>
</head>
<body>
    <p><a href="{% url 'film-list-html' %}">« Powrót do listy</a></p>
    <h2>Wyniki wyszukiwania dla: "{{ query }}"</h2>

    <form method="GET" action="{% url 'film-search-html' %}">
        <input type="text" name="q" value="{{ query }}" placeholder="Wpisz tytuł...">
        <button type="submit">Szukaj</button>
    </form>

    <hr>

    <ul>
        {% for f in filmy %}
            <li>
                <a href="{% url 'film-detail-html' f.id %}">{{ f.tytul }}</a> 
                ({{ f.rezyser.imie }} {{ f.rezyser.nazwisko }})
            </li>
        {% empty %}
            <li>Nie znaleziono filmów pasujących do zapytania.</li>
        {% endfor %}
    </ul>
</body>
</html>